runtime: go111

handlers:

# All URLs are handled by the Go application script
- url: /chat
  script: auto
  secure: always

- url: /room
  script: auto
  secure: always

- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$

- url: .*
  script: auto
