version: '3'
services:
  db:
    build: infra/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./infra/mysql/sql:/docker-entrypoint-initdb.d
    ports: 
      - "3316:3306"
